### ISSUE TITLE
Saturday 18th 03

### ISSUE THREAD

**Issue by oouazize** [dridslash/Web_server#5]
3awdt gadit dak l **main.cpp** 5dama b select() using FD_SET......
3andi class Config fih vector of Servers and each server fih directives and vector of Locations and each location fih directives
3andi class Request fih HTTPMethod, Path, HTTPVersion and Body and RequestParse() that parse the request file
3nadi class Response fih HTTPMethod, Path, HTTPVersion and Body likna5dhom mn Request w kayn Host, and Port li kna5dhom mn server side
and StatusCode w LocationIndex, the last one kn3mrha b index of server and location that match the path, and that path has been changed (ex: Path="/about/index.html", LocationPath="/About, "Root="public", NewPath="public/index.html") what happen is that we remove LocationPath form the Path and add RootPath at the beginnig of Path
Then, an every HTTPMethod function knbda ncheki wax rootpath s7i7 w moraha wax NewPath s7i7(kayn z3ma b stat() function) moraha knxof type of path wax directory or file
ila kan directory knxof wax fih / fl5r ila makanx fih k returni 301 w path fih / fl5r ila kan fih dik sa3a knxof wax kayn index files w wax s7a7 ila makanx knreturn 403 forbidden il kan, hna soit kan directory or file knxofo wax kayn cgi ila makanx knreturni dak path li hwa lfile li aytsift

**Comment by oouazize** [comment]
Aaaah nsit masiftx lik ports li atsayb bihom listener sockets

**Comment by oouazize** [comment]
mli anzido w tkml nta server side testi dakxi l function dyawli li aykono f main page homa requestParse() w responseFile() had function fiha kolxi w ktreturni lik string ta3 response

**Comment by oouazize** [comment]
nsit ba9ili lya deleteMethod w Post
Post andiro w n5li partya ta3 upload w andoz moraha CGI

**Comment by oouazize** [comment]
ports rahom m storyin f config

**Comment by dridslash** [comment]
rh ana li an parssi requet of multipart ol multiple file mchi nta, request rh mat parssach f string ola ththa kamla f file o tnod , rh khs tparssi m3a recv li kadir

**Comment by dridslash** [comment]
respone rh nta li at sendi mn server li ansawb , mohim momkin ntfahmo 3liha ola whd fina i sendi mymknch t sendi d9a whda

**Comment by oouazize** [comment]
multipart, multifile ??? wah 5as wnta kt9ra ktparsi

**Comment by dridslash** [comment]
o request rh fiha maydar mfihach gha parsi o sift , i think kna hdrna 3la hdchi , nta wjd gha response myzana mnin an upi server an disccusiw kifach nsiftoha , nta db parsi cgi o ntchekiw dik s3aa 3la l errors dylo ol use cases dyalo , ama request rh khsha t3awd structure dylha

**Comment by dridslash** [comment]
> multipart, multifile ??? wah 5as wnta kt9ra ktparsi

ah rh mchi kanjm3o hdchi 3d n parsiwh

**Comment by oouazize** [comment]
wah rah aytsanda rir bxwya ana knwjd l string w nta sendi b xwya

**Comment by dridslash** [comment]
khsna nfkro l dkchi mdrmin rh mablanch khsna nchofo request ach mhtaja

**Comment by dridslash** [comment]
rh request katjik kamla a shbi

**Comment by dridslash** [comment]
rh nta li kshk t managi kifach dir liha o b3d lmrat matjikch kamla

**Comment by dridslash** [comment]
mohim an9ad server o anbda n parssi request dik sa3a an3rf chno kaykon tmak o kifach data kat managa

**Comment by dridslash** [comment]
o zid 9ra 3la multiplexing ktr bch tfhmi ach kan3ni bch nkono f same page

**Comment by oouazize** [comment]
ok ana anxof db CGI

**Comment by oouazize** [comment]
Ok
