### ISSUE TITLE
Updates_March_28

### ISSUE THREAD

**Issue by dridslash** [dridslash/Web_server#7]
Css not working properly in Mozilla issue in response to work on after get request parsed you should work properly on the response

#Close_issuse_when_fixed

**Comment by oouazize** [comment]
ma3rftx 3lax kitra had lproblem mra i5dm mra la, swlt Mouad tahwoma trat lihom, i9dr itgad bohdo m3a lwa9t hit maymknx nsift lih css file w hwa ga3 masifthali f request

**Comment by dridslash** [comment]
ok m3a lw9t an3rfo ach kayn mohim andiro f balna hd l problem o sf
